version: '3.9'

services:
  mining:
    build: .
    ports:
      - 80:80 
    environment: 
      - "GITHUB_TOKEN=${GITHUB_TOKEN}"
      - "GITLAB_TOKEN=${GITLAB_TOKEN}"
      - "DATAFRAME_FILE=${DATAFRAME_FILE}"
    volumes:
      - ../data:/data